apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017 # see dockerhub mongo image
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret #secret.yaml-name: mongo-secret
              key: mongo-user #secret.yaml 
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password


# kind: Deployment
# blueprint for pods
# template- configurations for Pod
#   container: image
#              port 

---
apiVersion: v1
kind: Service # load balancer, forward traffic
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017 # does not matter what port, can be 80, 8080, etc.
      targetPort: 27017 # always containerPort, the port the service should forward requests to
#- internal port