apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongo-url: mongo-service


# ConfigMap Configuration 
# kind
# metadata/name - an arbitrary name
# data - the actual contents (key value pairs)